[project]
name = "cart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.38.22",
    "dbt-duckdb>=1.9.1",
]
